version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - run:
          name: Unit Test
          command: npm test
  linting:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - run:
          name: Lint Test
          command: eslint .

workflows:
  version: 2
  sample_pipeline:
    jobs:
      - linting
      - unit_test